"""
Twitter Link Strategy - Post text + YouTube link (generates preview automatically)
Bypasses the media upload paywall by using Twitter's link preview feature
"""

import logging
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).parent))

from platforms.twitter import TwitterPlatform
from creative_engine import CreativeEngine

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)


def post_with_link():
    """Post viral caption + YouTube link (Twitter shows video preview automatically)"""
    
    logger.info("=" * 60)
    logger.info("🐦 TWITTER: LINK PREVIEW STRATEGY")
    logger.info("=" * 60)
    
    # Generate viral caption
    logger.info("\n🎨 Step 1: Generating viral caption...")
    creative = CreativeEngine()
    
    topic = "Job #21 Completed: Rise Up NG - Nigeria is Building the Digital Future"
    caption = creative.generate_viral_caption(topic, platform='twitter')
    
    if not caption:
        logger.error("❌ Failed to generate caption")
        return None
    
    logger.info(f"✅ Caption: {caption}")
    
    # Append YouTube link
    youtube_link = "https://www.youtube.com/watch?v=MXSFpL_EhXg"
    
    # Combine caption + link (Twitter auto-generates preview)
    tweet_text = f"{caption}\n\n🎬 Watch: {youtube_link}"
    
    # Ensure under 280 chars
    if len(tweet_text) > 280:
        # Shorten caption to fit
        available_chars = 280 - len(f"\n\n🎬 Watch: {youtube_link}") - 3  # -3 for "..."
        tweet_text = f"{caption[:available_chars]}...\n\n🎬 Watch: {youtube_link}"
    
    logger.info(f"\n📝 Final tweet ({len(tweet_text)} chars):")
    logger.info(tweet_text)
    
    # Post to Twitter
    logger.info("\n🐦 Step 2: Posting to Twitter...")
    twitter = TwitterPlatform()
    
    if not twitter.client:
        logger.error("❌ Twitter not authenticated")
        return None
    
    try:
        response = twitter.client.create_tweet(text=tweet_text)
        
        tweet_id = response.data['id']
        tweet_url = f"https://twitter.com/amdsolutions007/status/{tweet_id}"
        
        logger.info("\n" + "=" * 60)
        logger.info("✅ SUCCESS! TWEET PUBLISHED WITH VIDEO PREVIEW")
        logger.info("=" * 60)
        logger.info(f"🐦 Tweet ID: {tweet_id}")
        logger.info(f"🔗 URL: {tweet_url}")
        logger.info(f"🎬 YouTube Preview: Auto-generated by Twitter")
        logger.info("=" * 60)
        logger.info("\n💡 Twitter will display the YouTube video thumbnail!")
        logger.info("Users can click to watch on YouTube.")
        
        return {
            'success': True,
            'tweet_id': tweet_id,
            'url': tweet_url,
            'text': tweet_text
        }
    
    except Exception as e:
        logger.error(f"❌ Post failed: {e}")
        return None


if __name__ == '__main__':
    result = post_with_link()
    
    if result:
        print(f"\n🎉 LIVE: {result['url']}")
    else:
        print("\n❌ Failed")
